In [2]:

import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

In [25]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [26]:
print("Score over time: " +  str(sum(rList)/num_episodes))


Score over time: 0.5595


In [22]:
print(Q)

[[1.24321477e-01 4.29487128e-03 2.19596941e-03 4.72103044e-03]
 [8.71241005e-04 1.53423580e-03 1.80452859e-04 1.15617700e-01]
 [1.63762182e-01 2.54796482e-03 4.44656965e-03 2.31824737e-03]
 [1.34926325e-04 3.98715161e-03 4.40844376e-04 1.95439366e-03]
 [1.18887844e-01 6.12030833e-03 3.77950741e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.23859919e-04 7.64107547e-06 2.35658828e-05 9.98959350e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.80931058e-05 1.44261850e-03 3.75421531e-01]
 [0.00000000e+00 6.97413205e-01 0.00000000e+00 0.00000000e+00]
 [9.08422610e-01 1.08889435e-03 6.66374812e-04 2.94206004e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.06623587e-01 0.00000000e+00]
 [0.00000000e+00 9.98300324e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000